classdef inputFig < handle
    
    properties (Constant)
        boxHeight = 0.05;
        boxWidth  = 0.07;
        sliderWidth = 0.5;
        sliderHeight = 0.03;
        horMargin = 0.01;
        verMargin = 0.01;
        fontSize  = 12;
        
        posMinMax = [-500 500;...
                     -500 500;...
                     -500 500];
        jointMinMax = [-180 180;...
                       -180 180;...
                       -180 180;...
                       -180 180;...
                       -180 180;...
                       -180 180];
    end
    
    properties
        % Graphics handles
        fig;
        posInput = gobjects(3,1);
        rotTabGroup;
        tabRotMat;
        tabEulZyx;
        matInput = gobjects(3,3);
        zyxInput = gobjects(3,1);
        configSelect;
        goButton;
        posSlider = gobjects(3,1);
        posSliderBox = gobjects(3,1);
        jointSlider = gobjects(6,1);
        jointSliderBox = gobjects(6,1);
    end
    
    methods
        function self = inputFig()
        end
        
        function createFigure(self)
            % close possible other instances of same figure
            hFigTemp = findobj(...
                'Type', 'Figure',...
                'Name', 'Robot Inputs');
            if ~isempty(hFigTemp)
                close(hFigTemp)
            end
            
            % create input figure
            self.fig = figure(...
                'Units',            'Normalized',...
                'OuterPosition',    [0.5, 0, 0.5, 0.5],...
                'Name',             'Robot Inputs',...
                'ToolBar',          'none',...
                'MenuBar',          'none',...
                'NumberTitle',      'off');
            
            %% Position input
%             uicontrol(...
%                 'Parent',           self.fig,...
%                 'Style',            'text',...
%                 'String',           'Position',...
%                 'Fontsize',         self.fontSize,...
%                 'Units',            'Normalized',...
%                 'Position',         [0, 1-self.boxHeight, 2*self.boxWidth+self.horMargin, self.boxHeight]);
            posStrings = {'x [mm]', 'y [mm]', 'z [mm]'};
            for ii = 1:3
                uicontrol(...
                    'Parent',           self.fig,...
                    'Style',            'text',...
                    'String',           posStrings{ii},...
                    'Fontsize',         self.fontSize,...
                    'Units',            'Normalized',...
                    'Position',         [0,...
                                         1-(ii+1)*self.boxHeight-ii*self.verMargin,...
                                         self.boxWidth,...
                                         self.boxHeight]);
                self.posInput(ii) = uicontrol(...
                    'Parent',           self.fig,...
                    'Style',            'edit',...
                    'String',           '0',...
                    'Fontsize',         self.fontSize,...
                    'Units',            'Normalized',...
                    'Position',         [self.boxWidth+self.horMargin,...
                                         1-(ii+1)*self.boxHeight-ii*self.verMargin,...
                                         self.boxWidth,...
                                         self.boxHeight]);
            end
            lastPos = self.posInput(3).Position;
            
            %% Rotation input
            self.rotTabGroup = uitabgroup(...
                'Parent',               self.fig,...
                'TabLocation',          'Top',...
                'Position',             [lastPos(1)+lastPos(3)+self.horMargin,...
                                         lastPos(2)-0.008,...
                                         3*self.boxWidth,...
                                         1-lastPos(2)]);
            % Rotation matrix input
            self.tabRotMat = uitab(...
                'Parent',               self.rotTabGroup,...
                'Title',                'matrix');
            rotMatTemp = eye(3);
            for ii = 1:3
                for jj = 1:3
                    self.matInput(ii,jj) = uicontrol(...
                        'Parent',           self.tabRotMat,...
                        'Style',            'edit',...
                        'String',           num2str(rotMatTemp(ii,jj)),...
                        'Fontsize',         self.fontSize,...
                        'Units',            'normalized',...
                        'Position',         [(jj-1)/3, 1-ii/3, 1/3, 1/3]);
                end
            end
            % Euler XYZ Input
            self.tabEulZyx = uitab(...
                'Parent',           self.rotTabGroup,...
                'Title',            'ZYX');
            rotString = {'Z [deg]', 'Y [deg]', 'X [deg]'};
            for ii = 1:3
                uicontrol(...
                    'Parent',           self.tabEulZyx,...
                    'Style',            'text',...
                    'String',           rotString{ii},...
                    'Fontsize',         self.fontSize,...
                    'Units',            'normalized',...
                    'Position',         [0, 1-ii/3, 1/2, 1/3]);
                self.zyxInput(ii) = uicontrol(...
                    'Parent',           self.tabEulZyx,...
                    'Style',            'edit',...
                    'String',           '0',...
                    'Fontsize',         self.fontSize,...
                    'Units',            'normalized',...
                    'Position',         [1/2, 1-ii/3, 1/2, 1/3]);
            end
            lastPos = self.rotTabGroup.Position;
            
            %% Configuration selector & 'GO-button'
            self.configSelect = uicontrol(...
                'Parent',           self.fig,...
                'Style',            'popupmenu',...
                'String',           cellfun(@num2str, num2cell(1:8),'UniformOutput',false),...
                'Value',            1,...
                'Fontsize',         self.fontSize,...
                'TooltipString',    'Joint configuration',...
                'Units',            'normalized',...
                'Position',         [lastPos(1)+lastPos(3)+self.horMargin,...
                                     1-2*self.boxHeight-self.verMargin,...
                                     self.boxWidth,...
                                     self.boxHeight]);
            self.goButton = uicontrol(...
                'Parent',           self.fig,...
                'Style',            'pushbutton',...
                'String',           'Go',...
                'Fontsize',         self.fontSize,...
                'Units',            'normalized',...
                'Position',         [lastPos(1)+lastPos(3)+self.horMargin,...
                                     1-4*self.boxHeight-3*self.verMargin,...
                                     self.boxWidth,...
                                     self.boxHeight],...
                'Callback',         @self.executeMove);
            
            %% Cartesian position sliders + number boxes
                
            for ii = 1:3
                self.posSlider(ii) = uicontrol(...
                    'Parent',           self.fig,...
                    'Style',            'slider',...
                    'Fontsize',         self.fontSize,...
                    'Units',            'normalized',...
                    'Position',         [self.horMargin,...
                                         lastPos(2)-(ii+1)*self.boxHeight-ii*self.verMargin,...
                                         self.sliderWidth,...
                                         self.boxHeight],...
                    'Min',              self.posMinMax(ii,1),...
                    'Max',              self.posMinMax(ii,2),...
                    'SliderStep',       [0.001 0.05],...
                    'Callback',         @self.executeMove);
                self.posSliderBox(ii) = uicontrol(...
                    'Parent',           self.fig,...
                    'Style',            'text',...
                    'String',           '0.00',...
                    'Fontsize',         self.fontSize,...
                    'Units',            'normalized',...
                    'Position',         [2*self.horMargin + self.sliderWidth,...
                                         lastPos(2)-(ii+1)*self.boxHeight-ii*self.verMargin,...
                                         self.boxWidth,...
                                         self.boxHeight],...
                    'Callback',         @self.executeMove);
                % add listener to update numeric value in posSlider
                % continuously, not only after release of mouse.
                addlistener(self.posSlider(ii) ,'Value', 'PostSet', ...
                    @(hObj, evtData) self.updateSliderValue(hObj, evtData, self.posSliderBox(ii)));
            end
            lastPos = self.posSlider(3).Position;
            

            %% Joint angle sliders + number boxes
            
            for ii = 1:6
                self.jointSlider(ii) = uicontrol(...
                    'Parent',           self.fig,...
                    'Style',            'slider',...
                    'Fontsize',         self.fontSize,...
                    'Units',            'normalized',...
                    'Position',         [self.horMargin,...
                                         lastPos(2)-(ii+1)*self.boxHeight-ii*self.verMargin,...
                                         self.sliderWidth,...
                                         self.boxHeight],...
                    'Min',              self.jointMinMax(ii,1),...
                    'Max',              self.jointMinMax(ii,2),...
                    'SliderStep',       [0.001 0.05],...
                    'Callback',         @self.executeMove);
                self.jointSliderBox(ii) = uicontrol(...
                    'Parent',           self.fig,...
                    'Style',            'text',...
                    'String',           '0.00',...
                    'Fontsize',         self.fontSize,...
                    'Units',            'normalized',...
                    'Position',         [2*self.horMargin + self.sliderWidth,...
                                         lastPos(2)-(ii+1)*self.boxHeight-ii*self.verMargin,...
                                         self.boxWidth,...
                                         self.boxHeight],...
                    'Callback',         @self.updateJoints);
                % add listener to update numeric value in posSlider
                % continuously, not only after release of mouse.
                addlistener(self.jointSlider(ii) ,'Value', 'PostSet', ...
                    @(hObj, evtData) self.updateSliderValue(hObj, evtData, self.jointSliderBox(ii)));
            end
            
            
            
        end
    end
    
    methods(Access=private)
        
        %% Callback from go-button, 
        % checks input validity and calls for move to location, if valid.
        function executeMove(self, hObj, ~)
            tolerance = 100*eps;
            % get input data
            switch self.rotTabGroup.SelectedTab.Title
                case 'matrix'
                    rotMatVal = reshape(cellfun(@str2num, {self.matInput.String}), [3,3]);
                case 'ZYX'
                    angleVal  = cellfun(@str2num, {self.zyxInput.String})';
                    angleVal  = angleVal*pi/180;
                    if ~any(isnan(angleVal))
                        rotMatVal = rotMat(angleVal(1), 'z') * rotMat(angleVal(2), 'y') * rotMat(angleVal(3), 'x');
                    else
                        rotMatVal = nan*eye(3);
                    end
            end
            
            % get position values, source depends on origin of callback
            if strcmp(hObj.Style, 'slider') % slider input
                posVal    = cellfun(@(x) x, {self.posSlider.Value})';
            else % editbox inputs
                posVal    = cellfun(@str2num, {self.posInput.String})';
            end
            
            % check if all inputs were numeric
            if any(any(isnan(rotMatVal))) || any(isnan(posVal))
                errordlg('Location inputs must be numeric', 'Invalid input');
                return
            end
            % check if rotation matrix is valid and right handed
            if isalmost(norm(rotMatVal), 1, tolerance) && ...
               isalmost(cross(rotMatVal(:,1), rotMatVal(:,2)), rotMatVal(:,3), tolerance)
                % MAKE ROBOT MOVE TO REQUESTED LOCATION
            else
                errordlg('Rotation matrix not normalized or right-handed', 'Invalid input')
                return
            end
        end
        
        
        %% update joint parameters
        function updateJoints(self, ~, ~)
            
        end
        
        
        %% generic slider listener for semi-continuous updating of current value
        function updateSliderValue(~, ~, eventdata, hValBox)
            hValBox.String = sprintf('%.2f', eventdata.AffectedObject.Value);
        end
    end
end

